version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  checkout_repo:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Checkout repository and commence flow"
          command: echo "Starting workflow"
  
  deploy_infra:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: UDACITY_ACCESS
          aws-secret-access-key: UDACITY_SECRET
          aws-region: AWS_REGION
      - run:
          name: Deploy Cloudformation stack
          command: |
            aws cloudformation deploy --stack-name StackViaCircleCI --template-file template.yml --parameter-overrides file://./template.json

workflows:
  workflow-1:
    jobs:
      - checkout_repo
      - deploy_infra
