Parameters:
  EnvironmentName:
    Description: Environment name?
    Type: String
    Default: Course2Exercise

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for mysql db
      DBSubnetGroupName: stackDBsubnetGroup
      SubnetIds: 
        - Fn::ImportValue: !Sub ${EnvironmentName}-PRSU1-ID
        - Fn::ImportValue: !Sub ${EnvironmentName}-PRSU2-ID
      Tags: 
        - Key: Name
          Value: !Sub ${EnvironmentName} db subnet group

  mySQLDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties: 
      AllocatedStorage: '20'
      AutoMinorVersionUpgrade: true
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: mysqladmin
      MasterUserPassword: udacitySQLdb
      DBName: udacitydbmysql
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PR-Security-Group
      DBSubnetGroupName: !Ref DbSubnetGroup
      DeletionProtection: true
      EnablePerformanceInsights: true
      Port: 3306
      PubliclyAccessible: false
      StorageType: gp2


