---
  - name: Update packages if necessary
    become: true
    become_method: sudo
    apt:
      update_cache: yes
  
  - name: Remove unused dependencies
    become: true
    apt:
      autoremove: yes
